# Generated by Django 3.1.7 on 2021-04-15 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=70, null=True, verbose_name='Last name')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Zip code')),
                ('job_title', models.CharField(max_length=100, null=True, verbose_name='Job Title')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=70, null=True, verbose_name='Position')),
                ('company_name', models.CharField(max_length=70, null=True, verbose_name='Organization')),
                ('description', models.CharField(blank=True, max_length=70, null=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End date')),
                ('resume_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=70, null=True, verbose_name='Organization')),
                ('description', models.CharField(blank=True, max_length=70, null=True, verbose_name='Description')),
                ('title', models.CharField(max_length=70, null=True, verbose_name='Title')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End date')),
                ('resume_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.resume')),
            ],
        ),
    ]
